title: Bagalavan Thurairatnam
logo: docs/assets/istockphoto-162959172-612x612.jpg
description: Mechanical Engineering Student| Building Controls | Drivetrain and Chassis Lead TASC
#show_downloads: true
theme: jekyll-theme-minimal
